version: '3.8'

services:
  vocabulary-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vocabulary-app
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - vocabulary-network

networks:
  vocabulary-network:
    driver: bridge 